Fix race condition in contracts.utilities.subscribeToEvent
LibertyDSNP/sdk-ts pull request #166
Opened 2021-09-01 15:41 UTC by wilwade

Problem
=======
In extremely rare cases, there could be a race condition with starting to get new posts, and getting older posts in subscribeToEvent.
[#179437626](https://www.pivotaltracker.com/story/show/179437626)

Solution
========
Checked again after starting to watch for new posts and removing duplicates in the overlap.

with @acruikshank 

Double Checks:
---------------
- [x] Did you update the changelog?
- [x] Any new modules need to be exported?
- [x] Are new methods in the right module?
- [x] Are new methods/modules in core or not (i.e. porcelain or plumbing)?
- [x] Do you have good documentation on exported methods?

2021-09-01 16:35 UTC, aneyzberg approved these changes
lgtm just one thought.

2021-09-01 16:35 UTC, aneyzberg commented on src/core/contracts/utilities.ts
> +  // Overlap is really unlikely, but possible.
it took me a minute to understand what was happening here. Not sure if a comment explaining what we are trying to achieve would be helpful?

2021-09-01 17:59 UTC, aneyzberg commented on src/core/contracts/utilities.ts
> +  // The time it takes to startup the provider.on might roll over a block boarder
this is super helpful! thank you. just a small typo in `border`

2021-09-01 20:10 UTC, wilwade commented on src/core/contracts/registry.test.ts
> +
Still trying to reduce that pesky flaky test

2021-09-01 20:14 UTC, aneyzberg approved these changes
got it. looks good.

2021-09-01 22:56 UTC, shannonwells requested changes
Changelog isn't updated, and also this is way more than just documentation.

2021-09-02 13:19 UTC, wilwade commented on src/core/contracts/registry.test.ts
>  import { generateHexString } from "@dsnp/test-generators";
Why all these changes to the registry test? Well a flaky test finally started failing consistently. The blockNumber wasn't always returning the correct value from the hardhat ganache with mineBlocks.

2021-09-02 13:20 UTC, wilwade commented
> Changelog isn't updated, and also this is way more than just documentation.

@shannonwells Good call. I finally got the flaky test not failing and forgot to update the PR and changelog. All updated now.

2021-09-02 18:57 UTC, shannonwells approved these changes

2021-09-02 18:58 UTC, merged