changed acceptable types in activity content, validation file
LibertyDSNP/sdk-ts pull request #182
Opened 2021-11-16 23:48 UTC by waylandli

Problem
=======
[Github issue #126 within spec](https://github.com/LibertyDSNP/spec/issues/126)
The sdk should reflect the changes made to the spec

Change summary:
---------------
- Changed accepted type within activitycontent/validation of audio/mp3 -> audip/mpeg
- Removed accepted type of image/jpg

2021-11-17 15:44 UTC, enddynayn approved these changes

2021-11-17 15:45 UTC, amparks100 approved these changes

2021-11-17 16:11 UTC, wilwade requested changes
Few things:
- Need to update the Changelog
- There are a few places we say "The MIME type of the file" such as in the factories. Could you do an update to that documentation to also mention something like "The MIME type of the file (see `SUPPORTED_AUDIO_MEDIA_TYPES`)"

2021-11-24 15:00 UTC, wilwade approved these changes

2021-11-29 17:52 UTC, merged