chore(batch): update reading batch function
LibertyDSNP/sdk-ts pull request #66
Opened 2021-06-15 00:31 UTC by enddynayn

Update #openURL function so that it matches
new interface from ParquetJS API.
    
As a result, of ParquetJS update the
request package is no longer needed since
the ParquetJS library uses fetch internally.

2021-06-16 20:12 UTC, shannonwells approved these changes

2021-06-18 15:19 UTC, wilwade requested changes
One double check

2021-06-18 15:19 UTC, wilwade commented on package.json
> -    "request": "^2.88.2",
Doesn't this require updating the `@dsnp/parquetjs` dependency?

2021-06-21 19:03 UTC, wilwade approved these changes
🎉

2021-06-21 19:23 UTC, merged